name: Docker Run
description: A GitHub Action to run a docker container with current workspace mapped and github actions env vars available.
inputs:
  image:  # id of input
    description: 'image name and tag'
    required: true
  run:
    description: 'commands to run on docker image. Uses -it options'
    required: false
  user:
    description: 'user to override image default'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
