name: Docker Run
description: A GitHub Action to run a docker container with current workspace mapped and github actions env vars available.
inputs:
  image:  # id of input
    description: 'image name and tag'
    required: true
  entrypoint:
    description: 'entrypoint to override image default'
    required: false
  commands:
    description: 'commands to run on docker image. Uses -it options'
    required: false
  user:
    description: 'user to override image default'
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash 
      run: >
        IMAGE="${{ inputs.image }}";
        ENTRYPOINT="${{ inputs.entrypoint }}";
        COMMANDS="${{ inputs.commands }}";
        USER="${{ inputs.user }}";
        
        CMD="docker run";
        if [ ! -z "$COMMANDS" ]; then; CMD="${CMD} -it"; fi;
        CMD="${CMD} --env-file $GITHUB_ENV";
        CMD="${CMD} --workdir /github/workspace -v $(echo $PWD):/github/workspace
        if [ ! -z "$USER" ]; then; CMD="${CMD} --user ${USER}"; fi;
        if [ ! -z "$ENTRYPOINT" ]; then; CMD="${CMD} --entrypoint ${ENTRYPOINT}"; fi;
        if [ ! -z "$IMAGE" ]; then; CMD="${CMD} ${IMAGE}"; fi;
        if [ ! -z "$COMMANDS" ]; then; CMD="${CMD} ${COMMANDS}"; fi;
        echo "Running: $CMD";
        `$CMD`;
