name: Docker Run
description: A GitHub Action to run a docker container with current workspace mapped and github actions env vars available.
inputs:
  image:  # id of input
    description: 'image name and tag'
    required: true
  entrypoint:
    description: 'entrypoint to override image default'
    required: false
  commands:
    description: 'commands to run on docker image. Uses -it options'
    required: false
  user:
    description: 'user to override image default'
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash 
      run: |
        echo hello
        IMAGE="${{ inputs.image }}";
        ENTRYPOINT="${{ inputs.entrypoint }}";
        COMMANDS="${{ inputs.commands }}";
        USER="${{ inputs.user }}";
        
        CMD="docker run --rm";
        CMD="${CMD} --env-file $GITHUB_ENV";
        echo "$CMD";
        CMD="${CMD} --workdir /github/workspace -v $(echo $PWD):/github/workspace";
        echo "$CMD";
        [ ! -z "$USER" ] && CMD="${CMD} --user ${USER}"
        echo "$CMD";
        [ ! -z "$ENTRYPOINT" ] && CMD="${CMD} --entrypoint ${ENTRYPOINT}"
        echo "$CMD";
        [ ! -z "$IMAGE" ] && CMD="${CMD} ${IMAGE}";
        echo "$CMD";
        [ ! -z "$COMMANDS" ] && CMD="${CMD} ${COMMANDS}";
        echo "Running: $CMD";
        `$CMD`
