name: Docker Run
description: A GitHub Action to run a docker container with current workspace mapped and github actions env vars available.
inputs:
  image:  # id of input
    description: 'image name and tag'
    required: true
  run:
    description: 'Bash commands to run on docker image. Overrides entrypoint of docker image to /bin/bash'
    required: false
  user:
    description: 'User to override image default'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
